In [26]:
# make sure to use DEBIAS (3.9.19) kernel

In [3]:
from debiasm import DebiasMClassifier
import debiasm
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

c:\Users\brean\miniconda3\envs\DEBIAS\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [151]:
np.random.seed(123)
n_samples = 96*5
n_batches = 5
n_features = 100

## the read count matrix
X = ( np.random.rand(n_samples, n_features) *1000).astype(int)

## the labels
y = np.random.rand(n_samples)>0.5

## the batches
batches = ( np.random.rand(n_samples) * n_batches ).astype(int)

In [4]:
type(y)

numpy.ndarray

In [5]:
batches

array([4, 4, 3, 3, 1, 2, 0, 1, 1, 4, 0, 2, 1, 4, 1, 1, 0, 4, 4, 4, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 3, 3, 0, 0, 2, 4, 2, 1, 4, 4, 4, 1, 1, 4, 2,
       1, 3, 4, 2, 4, 3, 4, 4, 2, 3, 1, 2, 2, 1, 1, 4, 3, 0, 3, 3, 0, 1,
       4, 0, 3, 3, 3, 2, 4, 1, 1, 0, 0, 3, 0, 4, 3, 1, 3, 2, 1, 3, 2, 4,
       3, 0, 2, 2, 1, 4, 4, 0, 4, 2, 1, 4, 1, 2, 2, 0, 2, 3, 3, 3, 1, 2,
       1, 2, 1, 2, 1, 3, 4, 4, 4, 0, 4, 4, 1, 4, 2, 2, 0, 3, 1, 0, 0, 3,
       3, 2, 4, 4, 3, 4, 4, 1, 3, 4, 2, 4, 4, 0, 4, 4, 2, 2, 2, 0, 2, 1,
       3, 4, 1, 4, 4, 1, 4, 1, 0, 2, 2, 3, 0, 4, 4, 4, 4, 4, 0, 0, 1, 0,
       4, 0, 1, 2, 1, 2, 2, 1, 3, 4, 3, 3, 4, 0, 3, 4, 0, 1, 3, 3, 0, 3,
       4, 4, 0, 3, 1, 3, 4, 3, 2, 2, 4, 0, 0, 4, 4, 4, 2, 4, 1, 3, 4, 0,
       3, 0, 0, 4, 3, 2, 2, 4, 4, 0, 2, 3, 1, 4, 0, 0, 1, 1, 1, 0, 4, 2,
       2, 4, 4, 1, 4, 2, 0, 4, 2, 2, 1, 3, 1, 3, 2, 4, 1, 2, 1, 0, 4, 1,
       3, 0, 2, 0, 2, 2, 2, 1, 1, 4, 1, 0, 4, 1, 0, 1, 3, 2, 0, 4, 0, 0,
       3, 0, 4, 1, 1, 3, 0, 3, 2, 3, 4, 4, 1, 3, 2,

In [6]:
## we assume the batches are numbered ints starting at '0',
## and they are in the first column of the input X matrices

X_with_batch = np.hstack((batches[:, np.newaxis], X))
X_with_batch[:10, :10]

array([[  4, 696, 286, 226, 551, 719, 423, 980, 684, 480],
       [  4, 513, 666, 105, 130, 321, 661, 846, 553, 854],
       [  3, 542,  66, 653, 996, 769, 573, 102, 699, 661],
       [  3,  16, 721,   7,  84, 225, 875, 363, 539, 568],
       [  1, 456, 279, 932, 314, 909,  43, 707, 483, 444],
       [  2, 212, 392, 851, 127, 893, 496, 426, 305, 916],
       [  0, 701, 707, 959, 876, 468, 625, 457, 222, 376],
       [  1, 945, 290, 727,  15, 879,  63, 733, 994, 501],
       [  1, 387, 555,  14, 847, 921, 550, 268, 990, 383],
       [  4, 896, 223, 268, 194, 967, 112, 722, 932, 668]])

In [7]:
## set the valdiation batch to '4'
val_inds = batches==4
X_train, X_val = X_with_batch[~val_inds], X_with_batch[val_inds]
y_train, y_val = y[~val_inds], y[val_inds]

In [8]:
dmc = DebiasMClassifier(x_val=X_val) ## give it the held-out inputs to account for
                                    ## those domains shifts while training

dmc.fit(X_train, y_train)
print('finished training!')

c:\Users\brean\miniconda3\envs\DEBIAS\lib\site-packages\pytorch_lightning\loops\utilities.py:91: PossibleUserWarning: `max_epochs` was not set. Setting it to 1000 epochs. To train without an epoch limit, set `max_epochs=-1`.
  rank_zero_warn(
c:\Users\brean\miniconda3\envs\DEBIAS\lib\site-packages\pytorch_lightning\trainer\connectors\callback_connector.py:151: LightningDeprecationWarning: Setting `Trainer(checkpoint_callback=False)` is deprecated in v1.5 and will be removed in v1.7. Please consider using `Trainer(enable_checkpointing=False)`.
  rank_zero_deprecation(
c:\Users\brean\miniconda3\envs\DEBIAS\lib\site-packages\pytorch_lightning\trainer\connectors\callback_connector.py:96: LightningDeprecationWarning: Setting `Trainer(progress_bar_refresh_rate=0)` is deprecated in v1.5 and will be removed in v1.7. Please pass `pytorch_lightning.callbacks.progress.TQDMProgressBar` with `refresh_rate` directly to the Trainer's `callbacks` argument instead. Or, to disable the progress bar pass 

finished training!


In [9]:
X_debiassed = dmc.transform(X_with_batch)
X_debiassed[:5, :5]

array([[0.01456792, 0.00533655, 0.00493307, 0.01202877, 0.01374545],
       [0.01067739, 0.01235743, 0.00227907, 0.0028221 , 0.00610232],
       [0.01087459, 0.00140587, 0.01448398, 0.02110646, 0.01628153],
       [0.00031825, 0.01522535, 0.00015392, 0.00176468, 0.0047226 ],
       [0.00967647, 0.00629353, 0.01726234, 0.00602933, 0.01834572]],
      dtype=float32)

## My own Data ##

### DEBIAS-M Leaky

In [9]:
np.random.seed(123)
log_DEBIAS = pd.read_csv("./csv_files/log_DEBIAS-M.csv") # read in data
data = log_DEBIAS.iloc[:,3:len(log_DEBIAS)] # select the case, Study ID (0-14), and data columns

data.head()

case  ID  X.Anaerorhabdus..furcosa.group  \
0  True   0                             0.0   
1  True   0                             0.0   
2  True   0                             0.0   
3  True   0                             0.0   
4  True   0                             0.0   

   X.Aquaspirillum..polymorphum.group  X.Bacteroides..pectinophilus.group  \
0                                 0.0                            0.000000   
1                                 0.0                            0.000000   
2                                 0.0                            0.000000   
3                                 0.0                            1.555367   
4                                 0.0                            0.000000   

   X.Clostridium..innocuum.group  X.Eubacterium..brachy.group  \
0                            0.0                          0.0   
1                            0.0                          0.0   
2                            0.0                          0.0   
3                            0.0                          0.0   
4                            0.0                          0.0   

   X.Eubacterium..eligens.group  X.Eubacterium..fissicatena.group  \
0                      2.736923                               0.0   
1                      2.411039                               0.0   
2                      3.349333                               0.0   
3                      2.244556                               0.0   
4                      2.398860                               0.0   

   X.Eubacterium..hallii.group  ...  Weissella  Wenxinia  Williamsia  \
0                     2.123979  ...   0.000000       0.0         0.0   
1                     1.579308  ...   0.000000       0.0         0.0   
2                     0.904502  ...   1.408091       0.0         0.0   
3                     1.358441  ...   0.729595       0.0         0.0   
4                     1.010379  ...   0.000000       0.0         0.0   

   Xanthobacter  Xanthomonas  XBB1006  Yersinia  Yokenella  Z20  Zymomonas  
0           0.0          0.0      0.0       0.0        0.0  0.0        0.0  
1           0.0          0.0      0.0       0.0        0.0  0.0        0.0  
2           0.0          0.0      0.0       0.0        0.0  0.0        0.0  
3           0.0          0.0      0.0       0.0        0.0  0.0        0.0  
4           0.0          0.0      0.0       0.0        0.0  0.0        0.0  

[5 rows x 923 columns]

In [10]:
## the read count matrix and "batches" a.k.a sample_IDs
X = data.iloc[:,2:len(data)]
X = X.to_numpy()

## select the labels
y =  data["case"].to_numpy() # the 0s and 1s... make sure true (case/1) false(control/0)

# batches
# batches = data.iloc[:,1:2]
# batches = batches.to_numpy()

# batches
batches = data.iloc[:, 1]
batches  = batches.to_numpy().astype(int)
batches


array([0, 0, 0, ..., 2, 2, 2])

In [12]:
## we assume the batches are numbered ints starting at '0',
## and they are in the first column of the input X matrices

# run this one without editing
# X_with_batch = np.hstack((batches[:, np.newaxis], X))
X_with_batch = np.hstack((batches[:, np.newaxis], X))
X_with_batch[:10, :10]
X_with_batch


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [2., 0., 0., ..., 0., 0., 0.],
       [2., 0., 0., ..., 0., 0., 0.],
       [2., 0., 0., ..., 0., 0., 0.]])

Run DEBIAS-M 15 times with 15 validation batches 
- will return 15 DEBIASED datasets and 15 weights
- RF on the 15 data sets with the testing on the val_inds 


In [13]:

## set the valdiation batch to '4'
# this means the training will be done without the fourth batch
# run this one without editing
val_inds = batches==4 
X_train, X_val = X_with_batch[~val_inds], X_with_batch[val_inds] 
y_train, y_val = y[~val_inds], y[val_inds]

In [157]:
print((X_train))
print("\n",X_val)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [2. 0. 0. ... 0. 0. 0.]
 [2. 0. 0. ... 0. 0. 0.]
 [2. 0. 0. ... 0. 0. 0.]]

 [[4. 0. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 ...
 [4. 0. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]]


In [14]:
# run this one without editing
dmc = DebiasMClassifier(x_val=X_val) ## give it the held-out inputs to account for
                                    ## those domains shifts while training



In [15]:
dmc.fit(X_train, y_train)
print('finished training!')

c:\Users\brean\miniconda3\envs\DEBIAS\lib\site-packages\pytorch_lightning\loops\utilities.py:91: PossibleUserWarning: `max_epochs` was not set. Setting it to 1000 epochs. To train without an epoch limit, set `max_epochs=-1`.
  rank_zero_warn(
c:\Users\brean\miniconda3\envs\DEBIAS\lib\site-packages\pytorch_lightning\trainer\connectors\callback_connector.py:151: LightningDeprecationWarning: Setting `Trainer(checkpoint_callback=False)` is deprecated in v1.5 and will be removed in v1.7. Please consider using `Trainer(enable_checkpointing=False)`.
  rank_zero_deprecation(
c:\Users\brean\miniconda3\envs\DEBIAS\lib\site-packages\pytorch_lightning\trainer\connectors\callback_connector.py:96: LightningDeprecationWarning: Setting `Trainer(progress_bar_refresh_rate=0)` is deprecated in v1.5 and will be removed in v1.7. Please pass `pytorch_lightning.callbacks.progress.TQDMProgressBar` with `refresh_rate` directly to the Trainer's `callbacks` argument instead. Or, to disable the progress bar pass 

finished training!


In [142]:
roc_auc_score(y_val, dmc.predict_proba(X_val)[:, 1]) 

0.6884969037342841

In [16]:
# run this one without editing

X_debiassed = dmc.transform(X_with_batch)
X_debiassed[:5, :5]

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.00748433, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [144]:
weights = dmc.model.batch_weights
print(weights)
np_weights = weights.detach().numpy()
np_weights.shape

# weights.to_csv("./csv_files/debias_weights.csv")

Parameter containing:
tensor([[ 0.0000,  2.7649, -1.2656,  ...,  0.0000, -0.2166,  0.0000],
        [ 0.0000,  0.0000,  1.6813,  ...,  0.0000, -2.7007,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 0.0000,  0.0000, -1.0686,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.6207,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.0253,  ...,  0.0000,  0.0000,  0.0000]],
       requires_grad=True)


(15, 921)

In [17]:
cols = list(data.columns[2:len(data)])

debiased_df = pd.DataFrame(data = X_debiassed,
                           columns = cols)

first_cols = log_DEBIAS.iloc[:, 0:3]

frames = [first_cols, debiased_df]

merged = pd.concat(frames, axis=1)

merged.to_csv("./csv_files/debiased_lognorm.csv", index = False)

merged


sample_name  Phenotype  Study_ID  \
0     10959.GBR00561.2011          1     10959   
1     10959.GBR00567.2011          1     10959   
2     10959.GBR00568.2011          1     10959   
3     10959.GBR00571.2011          1     10959   
4     10959.GBR00623.2011          1     10959   
...                   ...        ...       ...   
3597            15006.9C1          1     15006   
3598            15006.9F1          0     15006   
3599            15006.9M1          0     15006   
3600           15006.9SK1          0     15006   
3601           15006.9SM1          0     15006   

      X.Anaerorhabdus..furcosa.group  X.Aquaspirillum..polymorphum.group  \
0                                0.0                                 0.0   
1                                0.0                                 0.0   
2                                0.0                                 0.0   
3                                0.0                                 0.0   
4                                0.0                                 0.0   
...                              ...                                 ...   
3597                             0.0                                 0.0   
3598                             0.0                                 0.0   
3599                             0.0                                 0.0   
3600                             0.0                                 0.0   
3601                             0.0                                 0.0   

      X.Bacteroides..pectinophilus.group  X.Clostridium..innocuum.group  \
0                               0.000000                       0.000000   
1                               0.000000                       0.000000   
2                               0.000000                       0.000000   
3                               0.007484                       0.000000   
4                               0.000000                       0.000000   
...                                  ...                            ...   
3597                            0.000000                       0.026794   
3598                            0.000000                       0.000000   
3599                            0.000000                       0.000000   
3600                            0.000000                       0.000000   
3601                            0.000000                       0.000000   

      X.Eubacterium..brachy.group  X.Eubacterium..eligens.group  \
0                        0.000000                      0.016895   
1                        0.000000                      0.012346   
2                        0.000000                      0.022071   
3                        0.000000                      0.015359   
4                        0.000000                      0.012071   
...                           ...                           ...   
3597                     0.000000                      0.008587   
3598                     0.002645                      0.005697   
3599                     0.000000                      0.007866   
3600                     0.000000                      0.032703   
3601                     0.000000                      0.013123   

      X.Eubacterium..fissicatena.group  ...  Weissella  Wenxinia  Williamsia  \
0                              0.00000  ...   0.000000       0.0         0.0   
1                              0.00000  ...   0.000000       0.0         0.0   
2                              0.00000  ...   0.000467       0.0         0.0   
3                              0.00000  ...   0.000251       0.0         0.0   
4                              0.00000  ...   0.000000       0.0         0.0   
...                                ...  ...        ...       ...         ...   
3597                           0.00432  ...   0.000000       0.0         0.0   
3598                           0.00000  ...   0.000000       0.0         0.0   
3599                           0.00000  ...   0.000000       0.0         0

In [158]:
# Study_ID = pd.DataFrame(data = log_DEBIAS["Study_ID"].unique(),
#                         columns=["Study_ID"])
# weights_df = pd.DataFrame(data = np_weights,
#                           columns = cols)

# frames = [Study_ID, weights_df]

# weights_df = pd.concat(frames, axis = 1)
# weights_df["Study_ID"] = weights_df["Study_ID"].astype("category")
# weights_df.to_csv("./csv_files/debias_weights.csv")

# weights_df


Study_ID  X.Anaerorhabdus..furcosa.group  \
0     10959                        0.000000   
1     11129                        0.000000   
2     11210                        0.000000   
3     11635                       -1.896914   
4     11710                        2.515771   
5     11993                        0.000000   
6     13010                        0.000000   
7     13187                        0.000000   
8     13338                       -1.212751   
9     13631                        0.000000   
10    13652                        0.000000   
11    13695                        0.000000   
12    14130                        0.000000   
13    14669                        0.620668   
14    15006                        0.000000   

    X.Aquaspirillum..polymorphum.group  X.Bacteroides..pectinophilus.group  \
0                             2.764934                           -1.265646   
1                             0.000000                            1.681281   
2                             0.000000                            0.000000   
3                             0.000000                            1.630689   
4                             0.000000                            0.627875   
5                             0.000000                            0.000000   
6                             0.000000                           -4.088838   
7                             0.000000                            1.531150   
8                             0.000000                            0.126770   
9                             0.000000                            0.840419   
10                            0.000000                            0.000000   
11                            0.000000                           -1.147599   
12                            0.000000                           -1.068602   
13                            0.000000                            0.000000   
14                            0.000000                           -0.025347   

    X.Clostridium..innocuum.group  X.Eubacterium..brachy.group  \
0                        1.358705                     1.218808   
1                        3.984919                    -2.203013   
2                        1.958127                    -1.051986   
3                       -0.035764                    -2.957492   
4                        1.025706                    -0.323922   
5                       -1.210472                     0.522875   
6                        0.059340                    -2.129273   
7                       -1.714435                     1.905474   
8                       -1.404443                    -2.850213   
9                        2.346562                     1.398412   
10                      -0.432224                    -0.674228   
11                      -0.060109                    -1.231972   
12                       2.649692                     4.332458   
13                      -0.200680                    -1.775725   
14                       0.648599                     0.283822   

    X.Eubacterium..eligens.group  X.Eubacterium..fissicatena.group  \
0                      -0.808572                          0.654470   
1                       0.477271                          0.370220   
2                      -0.255628                         -0.648740   
3                      -0.486201                         -0.207958   
4                       0.749434                          1.387799   
5                      -0.793887                         -1.950767   
6                      -0.646098                          0.129568   
7                      -1.299735                          0.667357   
8                      -0.077395                         -0.803737   
9                      -0.257476                          1.606096   
10                     -0.363898                          0.502821   
11                      0.124140                          1.365655   
12                     -1.143686  

In [198]:
Study_ID = log_DEBIAS["Study_ID"].unique()

weights_df = pd.DataFrame(data = np_weights,
                          columns = cols,
                          index = Study_ID)

weights_df = weights_df.transpose()
weights_df.to_csv("./csv_files/debias_weights.csv")

weights_df



10959     11129     11210     11635  \
X.Anaerorhabdus..furcosa.group      0.000000  0.000000  0.000000 -1.896914   
X.Aquaspirillum..polymorphum.group  2.764934  0.000000  0.000000  0.000000   
X.Bacteroides..pectinophilus.group -1.265646  1.681281  0.000000  1.630689   
X.Clostridium..innocuum.group       1.358705  3.984919  1.958127 -0.035764   
X.Eubacterium..brachy.group         1.218808 -2.203013 -1.051986 -2.957492   
...                                      ...       ...       ...       ...   
XBB1006                             3.400071 -1.648795  0.000000  0.000000   
Yersinia                            0.000000  3.545854  0.000000  2.744119   
Yokenella                           0.000000  0.000000  0.000000  0.000000   
Z20                                -0.216586 -2.700722  0.000000 -0.994668   
Zymomonas                           0.000000  0.000000  0.000000  2.594330   

                                       11710     11993     13010     13187  \
X.Anaerorhabdus..furcosa.group      2.515771  0.000000  0.000000  0.000000   
X.Aquaspirillum..polymorphum.group  0.000000  0.000000  0.000000  0.000000   
X.Bacteroides..pectinophilus.group  0.627875  0.000000 -4.088838  1.531150   
X.Clostridium..innocuum.group       1.025706 -1.210472  0.059340 -1.714435   
X.Eubacterium..brachy.group        -0.323922  0.522875 -2.129273  1.905474   
...                                      ...       ...       ...       ...   
XBB1006                             0.000000  0.000000  4.412981  0.000000   
Yersinia                            0.000000  0.000000  0.000000  0.000000   
Yokenella                           0.000000  0.000000  0.000000  0.000000   
Z20                                 0.000000  0.000000 -0.686798  0.000000   
Zymomonas                           0.000000  0.000000  0.000000  0.000000   

                                       13338     13631     13652     13695  \
X.Anaerorhabdus..furcosa.group     -1.212751  0.000000  0.000000  0.000000   
X.Aquaspirillum..polymorphum.group  0.000000  0.000000  0.000000  0.000000   
X.Bacteroides..pectinophilus.group  0.126770  0.840419  0.000000 -1.147599   
X.Clostridium..innocuum.group      -1.404443  2.346562 -0.432224 -0.060109   
X.Eubacterium..brachy.group        -2.850213  1.398412 -0.674228 -1.231972   
...                                      ...       ...       ...       ...   
XBB1006                             0.000000  0.000000  0.000000 -1.391053   
Yersinia                            1.070979 -1.191989  2.622039  0.000000   
Yokenella                           0.000000  3.238680  0.000000  0.000000   
Z20                                 0.000000 -4.215164  0.000000 -3.574217   
Zymomonas                           0.000000  0.000000  0.000000  0.000000   

                                       14130     14669     15006  
X.Anaerorhabdus..furcosa.group      0.000000  0.620668  0.000000  
X.Aquaspirillum..polymorphum.group  0.000000  0.000000  0.000000  
X.Bacteroides..pectinophilus.group -1.068602  0.000000 -0.025347  
X.Clostridium..innocuum.group       2.649692 -0.200680  0.648599  
X.Eubacterium..brachy.group         4.332458 -1.775725  0.283822  
...                                      ...       ...       ...  
XBB1006                            -0.415355  0.000000  0.000000  
Yersinia                            0.000000  0.000000  0.000000  
Yokenella                           0.000000  0.000000  0.000000  
Z20                                 0.000000  0.000000  0.000000  
Zymomonas                           0.000000  0.000000  0.000000  

[921 rows x 15 columns]

In [18]:
i = 10
id_dict = {}
Study_ID = log_DEBIAS["Study_ID"].unique()
id_array = log_DEBIAS["ID"].unique()
for id in range(0,len(Study_ID)):
    id_dict[id_array[id]] = Study_ID[id]

type(id_dict)


In [114]:
debiased_df

X.Anaerorhabdus..furcosa.group  X.Aquaspirillum..polymorphum.group  \
0                                0.0                                 0.0   
1                                0.0                                 0.0   
2                                0.0                                 0.0   
3                                0.0                                 0.0   
4                                0.0                                 0.0   
...                              ...                                 ...   
3597                             0.0                                 0.0   
3598                             0.0                                 0.0   
3599                             0.0                                 0.0   
3600                             0.0                                 0.0   
3601                             0.0                                 0.0   

      X.Bacteroides..pectinophilus.group  X.Clostridium..innocuum.group  \
0                               0.000000                       0.000000   
1                               0.000000                       0.000000   
2                               0.000000                       0.000000   
3                               0.011283                       0.000000   
4                               0.000000                       0.000000   
...                                  ...                            ...   
3597                            0.000000                       0.021537   
3598                            0.000000                       0.000000   
3599                            0.000000                       0.000000   
3600                            0.000000                       0.000000   
3601                            0.000000                       0.000000   

      X.Eubacterium..brachy.group  X.Eubacterium..eligens.group  \
0                        0.000000                      0.016373   
1                        0.000000                      0.012030   
2                        0.000000                      0.022508   
3                        0.000000                      0.015702   
4                        0.000000                      0.012793   
...                           ...                           ...   
3597                     0.000000                      0.008962   
3598                     0.002167                      0.005647   
3599                     0.000000                      0.007248   
3600                     0.000000                      0.032289   
3601                     0.000000                      0.012552   

      X.Eubacterium..fissicatena.group  X.Eubacterium..hallii.group  \
0                             0.000000                     0.010655   
1                             0.000000                     0.006608   
2                             0.000000                     0.005097   
3                             0.000000                     0.007969   
4                             0.000000                     0.004519   
...                                ...                          ...   
3597                          0.004429                     0.012209   
3598                          0.000000                     0.005916   
3599                          0.000000                     0.002484   
3600                          0.000000                     0.003236   
3601                          0.000000                     0.009138   

      X.Eubacterium..nodatum.group  X.Eubacterium..oxidoreducens.group  ...  \
0                         0.000000                                 0.0  ...   
1                         0.000000                                 0.0  ...   
2                         0.000000                                 0.0  ...   
3                         0.000000                                 0.0  ...   
4                         0.000000                                 0.0  ...   
...                            ...                          

In [115]:
log_DEBIAS

sample_name  Phenotype  Study_ID   case  ID  \
0     10959.GBR00561.2011          1     10959   True   0   
1     10959.GBR00567.2011          1     10959   True   0   
2     10959.GBR00568.2011          1     10959   True   0   
3     10959.GBR00571.2011          1     10959   True   0   
4     10959.GBR00623.2011          1     10959   True   0   
...                   ...        ...       ...    ...  ..   
3597            15006.9C1          1     15006   True   2   
3598            15006.9F1          0     15006  False   2   
3599            15006.9M1          0     15006  False   2   
3600           15006.9SK1          0     15006  False   2   
3601           15006.9SM1          0     15006  False   2   

      X.Anaerorhabdus..furcosa.group  X.Aquaspirillum..polymorphum.group  \
0                                0.0                                 0.0   
1                                0.0                                 0.0   
2                                0.0                                 0.0   
3                                0.0                                 0.0   
4                                0.0                                 0.0   
...                              ...                                 ...   
3597                             0.0                                 0.0   
3598                             0.0                                 0.0   
3599                             0.0                                 0.0   
3600                             0.0                                 0.0   
3601                             0.0                                 0.0   

      X.Bacteroides..pectinophilus.group  X.Clostridium..innocuum.group  \
0                               0.000000                       0.000000   
1                               0.000000                       0.000000   
2                               0.000000                       0.000000   
3                               1.555367                       0.000000   
4                               0.000000                       0.000000   
...                                  ...                            ...   
3597                            0.000000                       0.487406   
3598                            0.000000                       0.000000   
3599                            0.000000                       0.000000   
3600                            0.000000                       0.000000   
3601                            0.000000                       0.000000   

      X.Eubacterium..brachy.group  ...  Wohlfahrtiimonas  Xanthobacter  \
0                        0.000000  ...                 0           0.0   
1                        0.000000  ...                 0           0.0   
2                        0.000000  ...                 0           0.0   
3                        0.000000  ...                 0           0.0   
4                        0.000000  ...                 0           0.0   
...                           ...  ...               ...           ...   
3597                     0.000000  ...                 0           0.0   
3598                     0.669462  ...                 0           0.0   
3599                     0.000000  ...                 0           0.0   
3600                     0.000000  ...                 0           0.0   
3601                     0.000000  ...                 0           0.0   

      Xanthomonas  XBB1006  Xylophilus  Yersinia  Yokenella  Z20  \
0             0.0      0.0           0       0.0        0.0  0.0   
1             0.0      0.0           0       0.0        0.0  0.0   
2             0.0      0.0           0       0.0        0.0  0.0   
3             0.0      0.0           0       0.0        0.0  0.0   
4             0.0      0.0           0       0.0        0.0  0.0   
...           ...      ...         ...       ...        ...  ...   
3597          0.0      0.0           0       0.0        0.0  0.0   
3598          0.0      0.0        